name = "dcn-manager"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# Configuration variables can be added here if needed in the future
